import React from 'react'
import { DocsThemeConfig } from 'nextra-theme-docs'

const config: DocsThemeConfig = {
  logo: <span>Original</span>,
  project: {
    link: 'https://github.com/Jolli-sample-repos/origin-error',
  },
  docsRepositoryBase: 'https://github.com/Jolli-sample-repos/origin-error',
  footer: {
    text: 'Original - Generated by Jolli',
  },
  useNextSeoProps() {
    return {
      titleTemplate: '%s – Original'
    }
  },
  head: (
    <>
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <meta property="og:title" content="Original" />
      <meta property="og:description" content="Documentation for Original" />
    </>
  )
}

export default config
